backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image H619 W1100", name: "imagePath", widget: "string" }
      - { label: "Image H300 W300", name: "imagePath1", widget: "string" }
      - { label: "Image H552 W414", name: "imagePath2", widget: "string" }
      - { label: "Image H480 W640", name: "imagePath3", widget: "string" }
      - { label: "Image H324 W576", name: "imagePath4", widget: "string" }
      - { label: "Image H360 W270", name: "imagePath5", widget: "string" }
      - { label: "Image H169 W300", name: "imagePath6", widget: "string" }
      - { label: "Image H250 W250", name: "imagePath7", widget: "string" }
      - { label: "Image H186 W248", name: "imagePath8", widget: "string" }
      - { label: "Image H144 W256", name: "imagePath9", widget: "string" }
      - { label: "File Format", name: "format", widget: "string" }
      #- name: featured_image
        #label: Original Featured image
        #widget: object
        #fields:
          #- { name: src, label: Image, widget: image }
          #- { name: alt, label: Alt text, widget: string }
          #- { name: title, label: Title, widget: string }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["pharmacyinformatics", "healthinformationtechnology", "healthinformatics", "pharmacyresidency", "pharmacystudent", "medicationsafety", "pharmacyautomation"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
